spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogs?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名转换
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qfedu.pojo