spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名转换